name: 'Python Coverage'
description: 'Publish coverage report to a PR or push & enforce coverage on new & modified files'
author: 'orgoro'
inputs:
  coverageFile:
    required: true
    description: 'local path to a coverage xml file like the output of pytest --cov'
  token:
    required: true
    description: 'github token'
  thresholdAll:
    required: false
    description: the coverage threshold for average over all files [0,1]
    default: 0.0
  thresholdNew:
    required: false
    description: the coverage threshold for average over new files [0,1]
    default: 0.0
  thresholdModified:
    required: false
    description: the coverage threshold for average over new files [0,1]
    default: 0.0
  sourceDir:
    required: false
    description: the directory to use as the source of the coverage report
  title:
    required: false
    description: the title of the report, preferably unique to the  PR/push
  passIcon:
    required: false
    description: the indicator to use for files that passed
    default: '🟢'
  failIcon:
    required: false
    description: the indicator to use for files that failed
    default: '🔴'
  include-all-files:
    required: false
    description: whether to include coverage details for all files, not just modified/new ones
    default: 'true'
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
   icon: 'umbrella'
   color: 'purple'
